language: node_js
node_js:
- '8.1'
install:
- npm cache verify
- npm install
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAIIXX4W3H2XG43PNQ
  secret_access_key:
    secure: pgCfJ1ojgCQOjIRydusWgI2pUZq2tDfehxpGmQpbW0DDcKuc9xHCsJgnhiPEe/V+l8Ny0hzfCXCBV+sQHLBKWTWOA5o2hzaEloJGTz0e9Z/acJ1vgM7cK/drYFb2ZK6ivtygMGPl2Kg2EdwQpnDe8UIU12+wEB/ftuv4qlInvNiL0Lww0GDXAnHDdezQRQcW3rKBISvd2PDrsvOP/nbo4248JLo/IAU6ozrk0CwE0/4E/GdZo3jnMVmLOnc1fD1g0xEXRHOVcP4GpfjuHntd6gdTb8ghguDhb0uC+YxikARZLzrvTL06IzeShQtOW6n+7yf6hrQn58MDO88wspLSFA7MBQFqtNgCkV0imKQKwwr0mNk4rcfF1rReyLuenS7rEIsByaMXQgK28Tvz1QcmsDwVuGKeF6vZkEV2cjFxQ7vvW1RDgKo2LvBX9IWn8ln0JvMUMEy9pnxyUErgQqmcPZK11OvTNV8+FZSQZ3dnzf6vDC1s2USHDYJUHdYnizOeKRkALhIDn6gAI26TgIX9zsfv4bhfSlydqu08Ukvf5PBrnLP2LS/5ihy0nte0R0zczLZKGLfJdFm8iWNKY67KUBl2tV5Zf8jsMecOshR6QlS6X40T0iD3h9RZXGgPC88hhLg4H6mErumqLi20IomGVP2U2jSclj9IWdy8riPXQdQ=
  bucket: tttoe
  skip_cleanup: true
  region: eu-west-1
  local_dir: build
  on:
    repo: taquiles/tttoe
