language: node_js
node_js:
- '8.1'
install:
- npm cache verify
- npm install
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAIIXX4W3H2XG43PNQ
  secret_access_key: 
    secure: OrG8/c/szuLrusvLtzmNQZQSwTuBK2beKB5WewrLuRB/dFWvOt+GIQy2vpEQ8QzB46r+ATBhQRaYaz4g5BIX87r+Lv2gAyoexBUgTigEHGZW/5b4Xk5mGFw+rAfXElDp60k7/WEm6jX776FMlT7i4n+qenAJ6tfaBc05mf36RO5dfu72UZVujhGE5zS+7YFQLtLb8C7Lgguo35Pd6U36vTr2isIalsyY523kq3kCAy4dgjGUP/vfft+AWfHB9iZAh2NQLTBgpoWTwGmwbebWF6IqawA56zilwK54KXZ9VTKsQFSfGoQXazDqsQhGc70p/N5y/UgFg4r/qhKLn/GHL6vugbKlOwZt6BotCB/5maUCruIfn+TrQkIDQQbNQsSpNL8347icH4Ogp4vENoirnUB2S804tSilps+o2kySfPLaNpg2EivebhyQ4gl06Q6wDaTrQkH/N8rO/l9N0+iYOr4iDnbNhwc8jj1JY//Aq7Vh1UVohvrSkOWEr0W2ekjTHjb5+TdQnMDX4jjVMcRbjbpWLLhGVEMwjlbSF/AyZLtdlZ6VK29bWZaHRuYgT+ITX2kZZkPZ5xBAe+6GwjvgT28u+bv74Jg/pgj35O8QuqJy9VWbUAG90c96wyix7HVSQF5LgXQl2Fir6GYKzTrmcDs38YUO38FNQ80FRwkw0uo=
  bucket: tttoe
  skip_cleanup: true
  region: eu-west-1
  local_dir: build
  on:
    repo: taquiles/tttoe
