language: node_js
node_js:
- '8.1'
install:
- npm cache verify
- npm install


## Travis CI can cache content that does not often change, 
## https://docs.travis-ci.com/user/caching/cache:cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAIIXX4W3H2XG43PNQ
  secret_access_key:
    secure: Lb9J4m4D9yQ4M9qdhJ3fveu2YDcuRZ3iBxv76TuQwfBdXpkfQ+xq0Nj/FbL/0xLv1tlraojbY54yXn4VvJAd4BsOjT4zj3gdMZOF3hp5l/EOdmiIsw4MDD9cx007aPFF7KIs4CFA+BEMCLl9dSg13NRuLxnFvk+0cSFCAL1AB9xLTn3taROIUf8SmXLmyg0YxWqwE1ro5sPLscIS/+1S/K+2tJ57YCgtrjQKl9UVbiqr0vzKYz+woZB9XgkvbL3vwkGsG8XgAbUI7GxK+hsdH8OXT6EbLubxcJFlnjHrepVlcEkD3koA3uE2q4WD7weW65QF1HmEzb1ncXKZLH0Zs0KS/sIz3dN2QUofZp0NPuj+UpHG0PRgDQS65eTpO/OTGk/R20XV9jK8jUwAUa8vD1WfBdzAd73TOJVsdsnm18alAqMn5E3SO6NmwzSZnTcbImf+4LZQsw4IXY3IkqFpHlnbNit3yYAvp30iwuri3p3eSFGS/Olsw0PcaFQlMUfFMpXOh3kgOzbsc2tMSEEo/yHE6h/l6gwhsr3iFVUGGjY46s3Hh1QyZEjubZ6ZX26g9iFY6Emm6Jmlb4TWsRvXwwzy7lM1nbpAOysbgyBu3QMnvlCNMnSG/Sc4IvnxvcNs2yIYejLtxw4A0z3ZmWVdG1R1r8q2tBXeaKAyfx/ZZWU=
  bucket: tttoe
  skip_cleanup: true
  region: eu-west-1
  local_dir: build
  on:
    repo: taquiles/tttoe
